### ISSUE TITLE
gifs v3 support

### ISSUE THREAD

**Issue by RedDeadRandy** [ubershmekel/redditp#152]
videos from redgifs no longer play. 

thanks in advance

**Comment by ubershmekel** [comment]
https://www.redditp.com/domain/redgifs.com seems to work. Do you have an example of a url that's not working?

**Comment by RedDeadRandy** [comment]
Yep, it's working. 

Before creating this I thought to myself, don't post an issue without some due diligence so you don't look like a moron or waste someone's time. Tested with Firefox/Chrome on two different machines on separate connections (one residential cable, one cellular). Same results.

Sorry for jumping the gun.

**Comment by dirty-alt** [comment]
Not working for me still. (https://www.redditp.com/domain/redgifs.com)
IIRC this started about a week ago, just thought that it would get fixed by now. 😅

Tested not working:
- ungoogled-chromium, incognito and normal browsing (Version 109.0.5414.120 (Official Build, ungoogled-chromium) (64-bit))
- Google Chrome, incognito and normal browsing (Version 109.0.5414.120 (Official Build) (64-bit))

Weirdly enough, on FF 108.0.1 (64-bit) it seems to work *just fine* with private and normal browsing.

On chrome, all I get is the deep blue background of redgifs and an error in the console (no red error box in upper right either):

```
Ajax requesting: https://www.reddit.com/domain/redgifs.com.json?
application-state.ts:29 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://www.redgifs.com/static/js/main.a50fb6a7.js:2:548597
    at https://www.redgifs.com/static/js/main.a50fb6a7.js:2:1705868
    at https://www.redgifs.com/static/js/main.a50fb6a7.js:2:1705871
(anonymous) @ application-state.ts:29
(anonymous) @ index.tsx:58
(anonymous) @ index.tsx:58
```

Quick Googling showed that is an error for 3rd party cookies on a site, but I have redgifs.com (and for good measure redditp.com) -domain whitelisted for third party cookies (wiped on close though).
My error is thrown when the redgifs application-state.ts tries to read localStorage for playback-quality stuff.

Also, thanks for maintaining this 'viewer' for all these years! Been a staple of my browsing for a loooong time. 👍😍

**Comment by ubershmekel** [comment]
I didn't think of trying this out in incognito. I can produce the problem now, thank you. I'll take a look.

**Comment by ubershmekel** [comment]
Strangely, redditp is working fine in incognito mode. Seems it's redgifs that's failing. Actually, it just took 19.39 seconds to load this url:

https://www.redgifs.com/ifr/alarmingjubilantdogwoodclubgall

Then in that same incognito window, suddenly the other redgifs iframes are fast to load in their own tab. But on redditp, the iframes never load correctly. One thing that's different about the iframe on redditp is that they load these files:

https://www.redgifs.com/cdn-cgi/challenge-platform/h/b/scripts/alpha/invisible.js?ts=1676232000

https://www.redgifs.com/cdn-cgi/challenge-platform/h/b/scripts/pica.js

Googling those url parts brings up https://developers.cloudflare.com/fundamentals/get-started/reference/cdn-cgi-endpoint/

Which mentions:

> JavaScript detection used by Cloudflare bot products (example.com/cdn-cgi/challenge-platform/)

Maybe redgifs is using some sort of [iframe protection](https://developers.cloudflare.com/workers/examples/security-headers)? Maybe Chrome in incognito is somehow causing cloudflare to think it's a bot.
